name: E2E Tests
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: portfolio/portfolio
          path: portfolio
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: E2E on Chrome
        uses: cypress-io/github-actions@v2
        with:
          browser: chrome
