name: E2E Tests
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
            node-version: '12'
            cache: 'npm'
      - name: Cypress Portfolio E2E
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          project: /portfolio-e2e
